///<reference types="cypress"/>
import 'cypress-file-upload';

describe('EVEX7 test', () => {

    beforeEach(() => {
        // funcao pra ser inicializada sempre antes de todos os testes, 
        cy.clearLocalStorage()
        cy.viewport(1440, 900);
        cy.visit('/')
        cy.get('#loginForm h4').should('have.text', 'Seja bem-vindo ao EVEX7!')
        cy.login(Cypress.env('loginInpt'), Cypress.env('pwd'))
        cy.url().should('eq', 'http://localhost:8080/sav-web-1.0/inicio.faces')
        cy.get('.menu-button > .pi').should('be.visible').then(() => { cy.wait(500) });
        cy.get('.menu-button > .pi').click()
        cy.wait(500)
    })

    context('Tela Simulacao Web', () => {
        // it('Nova Simulacao - Pesquisar ', () => {
        //     cy.acaoSimulacaoWeb()
        //     cy.get('input[id="nomeCliente2"]').type('ENO2G60')
        //     cy.get('button[id="btnPesquisar"]').click()
        // })

        // it('Nova Simulacao - Limpar ', () => {
        //     cy.acaoSimulacaoWeb()
        //     cy.get('input[id="nomeCliente2"]').type('ENO2G60')
        //     cy.get('button[id="btnPesquisar"]').click()
        //     cy.get('button[id="btnLimpar"]').should('be.visible').contains("Limpar").click()
        // })
    })

    context('Tela Simulacao Web', () => {
        var cotacaoWeb = require('../../fixtures/cotacaoWeb.json')
        cotacaoWeb.forEach(cotacaoWeb => {
            // it.skip(`Nova Simulacao - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('button[id="j_idt392"]').click()
            //     cy.get('label[id="regional_label"]').click()
            //     cy.get('li[data-label="MG.70"]').click()
            //     cy.get('label[id="consultor_label"]').click()
            //     cy.get('li[id="consultor_5"]').click()
            //     cy.get('label[id="estadoCirculacao_label"]').click()
            //     cy.get('li[data-label="Minas Gerais"]').click()
            //     cy.get('label[id="municipioCirculacao_label"]').click()
            //     cy.get('li[data-label="Belo Horizonte"]').click()                 
            //     cy.get('label[id="anoM_label"]').click()
            //     cy.get('li[data-label="2016"]').click()
            //     cy.get('input[id="fipeModelos_input"]').type('civic')
            //     cy.get('[data-item-value="CIVIC SEDAN LXR 2.0 FLEXONE 16V AUT. 4P 014074-0 Gasolina"]').click()
            //     cy.get('label[id="tipoCota_label"]').click()
            //     cy.get('li[data-label="VEICULO LEVE - GO - PLANO FLEX - 03/17"]').click()              
            //     cy.get('button[id="incluirCotacaoValor"]').click()
            //     cy.get('input[id="nomeCliente"]').type(cotacaoWeb.nomeProponente)                
            //     cy.get('input[id="placa"]').type(cotacaoWeb.placa)    
            //     cy.get('input[id="email_input"]').type(cotacaoWeb.email)    
            //     cy.get('input[id="telefone"]').type(cotacaoWeb.celular)
            //     cy.get('button[id="salvar"]').contains("Salvar").should('be.visible').click()
            // })

            // it(`Cotação - Pesquisar - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnEditar"]').click()
            //     cy.get('label[for="emailCliente:0"]').click()
            //     cy.get('button[id="salvar"]').click()
            // })
            
            // it(`Cotação - Consultar - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnConsultar"]').click()
            //     cy.wait(3500)
            //     cy.get('button[id="j_idt834"]').click()
            // })

            // it(`Adesao - Selecionar o Plano- ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnAdesao"]').click()
            //     cy.get('label[id="cotacaoCotaValores_label"]').click()
            //     cy.get('li[id="cotacaoCotaValores_1"]').click()
            //     cy.get('button[id="inserirDadosPlano"]').click()
            //     cy.wait(3500)
            // })

            // it(`Adesao - Dados do Proponente - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnAdesao"]').click()
            //     cy.get('input[id="cpfCnpjClienteAdesao"]').type(cotacaoWeb.cpf)
            //     cy.wait(500)
            //     cy.get('input[id="docCnh"]').type(cotacaoWeb.cnh)
            //     cy.get('label[id="sexoRadio_label"]').should('be.visible').click()
            //     cy.get('li[id="sexoRadio_2"]').click()
            //     cy.get('input[id="dataNascimento_input"]').click().type('01021980')
            //     cy.get('input[id="telefone2"]').clear().type(cotacaoWeb.celular)
            //     cy.get('input[id="docIdentidade"]').type(cotacaoWeb.docIdentidade)
            //     cy.get('label[id="orgaoEmissor_label"]').click()
            //     cy.get('li[id="orgaoEmissor_29"]').click()
            //     cy.get('label[id="estadoComboNat_label"]').click()
            //     cy.get('li[id="estadoComboNat_13"]').click()
            //     cy.get('label[id="cidadeComboNat_label"]').click()
            //     cy.get('li[id="cidadeComboNat_1"]').click()
            //     cy.get('button[id="btnContinuar"]').click()
            //     cy.wait(3500)
            // })

            // // it.only(`Adesao - Endereco - ${cotacaoWeb.nomeProponente}`, () => {
            // //     cy.acaoSimulacaoWeb()
            // //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            // //     cy.get('button[id="btnPesquisar"]').click()
            // //     cy.wait(500)
            // //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            // //     cy.get('a[id="tabelaResultado:0:btnAdesao"]').click()
                
            // //     cy.wait(3500)
            // // })

            // it(`Adesao - Veiculo - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnAdesao"]').click()
            //     cy.wait(500)
            //     cy.get('input[id="renavam"]').type(cotacaoWeb.renavam)
            //     cy.get('input[id="numeroChassi"]').type(cotacaoWeb.chassi)
            //     cy.get('label[id="categoria_label"]').click()
            //     cy.get('li[data-label="VEÍCULOS DE PASSEIO - NACIONAL"]').click()
            //     cy.get('label[id="anoFabricacao_label"]').click()
            //     cy.get('li[id="anoFabricacao_1"]').click()
            //     cy.get('label[id="cor_label"]').click()
            //     cy.get('li[id="cor_11"]').click()
            //     cy.get('label[id="combustivel_label"]').click()
            //     cy.get('li[id="combustivel_5"]').click()
            //     cy.get('label[id="diaVencimento_label"]').click()
            //     cy.get('li[id="diaVencimento_4"]').click()
            //     cy.get('label[for="optarBoletoDigital:0"]').click()
            //     cy.get('#copiarValDut').click()
            //     cy.get('label[id="anoExercicioCrlv_label"]').click()
            //     cy.get('li[id="anoExercicioCrlv_1"]').click()
            //     cy.get('input[id="numeroChassi"]').type(cotacaoWeb.chassi)
            //     cy.get('button[id="inserirDadosVeiculo"]').click()
            //     cy.get('button[id="inserirDadosVeiculo"]').click()
            //     // cy.wait(3500)
            // })

            // it(`Adesao - Assinatura - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnAdesao"]').click()
            //     cy.wait(500)
            //     cy.get('label[for="aceitoRegulamento:0"]').click()
            //     cy.get('label[for="assinaturaVirtual:1"]').click()
            //     // cy.wait(3500)
            // })

            // it(`Adesao - Arquivo - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnAdesao"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="inserirDadosAssinatura"]').click()
            //     cy.get('button[id="j_idt1742"]').click()
            //     cy.wait(3500)
            // })

            // it(`Adesao - Resumo - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnAdesao"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="finalizarResumo"]').click()
            //     cy.wait(3500)
            // })

            it.skip(`Nova Simulacao - ${cotacaoWeb.nomeProponente}`, () => {
                cy.acaoSimulacaoWeb()
                cy.get('button[id="j_idt392"]').click()
                cy.get('label[id="regional_label"]').click()
                cy.get('li[data-label="MG.70"]').click()
                cy.get('label[id="consultor_label"]').click()
                cy.get('li[id="consultor_5"]').click()
                cy.get('label[id="estadoCirculacao_label"]').click()
                cy.get('li[data-label="Minas Gerais"]').click()
                cy.get('label[id="municipioCirculacao_label"]').click()
                cy.get('li[data-label="Belo Horizonte"]').click()                 
                cy.get('label[id="anoM_label"]').click()
                cy.get('li[data-label="2016"]').click()
                cy.get('input[id="fipeModelos_input"]').type('civic')
                cy.get('[data-item-value="CIVIC SEDAN LXR 2.0 FLEXONE 16V AUT. 4P 014074-0 Gasolina"]').click()
                cy.get('label[id="tipoCota_label"]').click()
                cy.get('li[data-label="VEICULO LEVE - GO - PLANO FLEX - 03/17"]').click()              
                cy.get('button[id="incluirCotacaoValor"]').click()
                cy.get('input[id="nomeCliente"]').type(cotacaoWeb.nomeProponente)                
                cy.get('input[id="placa"]').type(cotacaoWeb.placa)    
                cy.get('input[id="email_input"]').type(cotacaoWeb.email)    
                cy.get('input[id="telefone"]').type(cotacaoWeb.celular)
                cy.get('button[id="salvar"]').contains("Salvar").should('be.visible').click()
            })

            // it(`Cotação - Pesquisar - ${cotacaoWeb.nomeProponente}`, () => {
            //     cy.acaoSimulacaoWeb()
            //     cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
            //     cy.get('button[id="btnPesquisar"]').click()
            //     cy.wait(500)
            //     cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
            //     cy.get('a[id="tabelaResultado:0:btnEditar"]').click()
            //     cy.get('label[for="emailCliente:0"]').click()
            //     cy.get('button[id="salvar"]').click()
            // })
            
            it(`Adesao - Selecionar o Plano- ${cotacaoWeb.nomeProponente}`, () => {
                cy.acaoSimulacaoWeb()
                cy.get('input[id="nomeCliente2"]').type(cotacaoWeb.nomeProponente)
                cy.get('button[id="btnPesquisar"]').click()
                cy.wait(500)
                cy.get('button[id="tabelaResultado:0:botoesMobile_button"]').click()
                cy.get('a[id="tabelaResultado:0:btnAdesao"]').click()
                cy.get('label[id="cotacaoCotaValores_label"]').click()
                cy.get('li[id="cotacaoCotaValores_1"]').click()
                cy.get('button[id="inserirDadosPlano"]').click()
                cy.get('input[id="cpfCnpjClienteAdesao"]').clear().type(cotacaoWeb.cpf)
                cy.wait(500)
                cy.get('input[id="docCnh"]').type(cotacaoWeb.cnh)
                cy.get('label[id="sexoRadio_label"]').should('be.visible').click()
                cy.get('li[id="sexoRadio_2"]').click()
                cy.get('input[id="dataNascimento_input"]').click().clear().type('01021980')
                cy.get('input[id="telefone2"]').clear().type(cotacaoWeb.celular)
                cy.get('input[id="docIdentidade"]').clear().type(cotacaoWeb.docIdentidade)
                cy.get('label[id="orgaoEmissor_label"]').click()
                cy.get('li[id="orgaoEmissor_29"]').click()
                cy.get('label[id="estadoComboNat_label"]').click()
                cy.get('li[id="estadoComboNat_13"]').click()
                cy.get('label[id="cidadeComboNat_label"]').click()
                cy.get('li[id="cidadeComboNat_1"]').click()
                cy.get('button[id="btnContinuar"]').click()
                cy.get('input[id="cep"]').clear().type('331110000')
                cy.get('input[id="endereco"]').clear().type('rua tal')
                cy.get('input[id="numeroEndereco"]').clear().type('5')
                cy.get('input[id="nomeBairro"]').click()
                cy.get('label[id="estadoCombo_label"]').click()
                cy.get('li[data-label="Minas Gerais"]').click()
                cy.get('label[id="cidadeCombo_label"]').click()
                cy.get('li[data-label="Belo Horizonte"]').click()
                cy.get('button[id="btnVoltarAssociado"]').click()
                cy.get('input[id="renavam"]').clear().type(cotacaoWeb.renavam)
                cy.get('input[id="numeroChassi"]').clear().type(cotacaoWeb.chassi)
                cy.get('label[id="categoria_label"]').click()
                cy.get('li[data-label="VEÍCULOS DE PASSEIO - NACIONAL"]').click()
                cy.get('label[id="anoFabricacao_label"]').click()
                cy.get('li[id="anoFabricacao_1"]').click()
                cy.get('label[id="cor_label"]').click()
                cy.get('li[id="cor_11"]').click()
                cy.get('label[id="combustivel_label"]').click()
                cy.get('li[id="combustivel_5"]').click()
                cy.get('label[id="diaVencimento_label"]').click()
                cy.get('li[id="diaVencimento_4"]').click()
                cy.get('label[for="optarBoletoDigital:0"]').click()
                cy.get('#copiarValDut').click()
                cy.get('label[id="anoExercicioCrlv_label"]').click()
                cy.get('li[id="anoExercicioCrlv_1"]').click()
                cy.get('input[id="numeroChassi"]').clear().type(cotacaoWeb.chassi)
                cy.get('button[id="inserirDadosVeiculo"]').click()
                cy.get('button[id="j_idt1359"]').click()
                cy.get('label[for="aceitoRegulamento:0"]').click()
                cy.get('label[for="assinaturaVirtual:1"]').click()
                cy.get('button[id="inserirDadosAssinatura"]').click()
                cy.get('button[id="j_idt1742"]').click()
                cy.get('button[id="finalizarResumo"]').click()
                cy.wait(3500)
            })

        })  
    })

})
        